Supplier.create(name: "Nike", email: "support@nike.com", phone_number: 18008066453)
Supplier.create(name: "Adidas", email: "help@adidas.com", phone_number: 18009829337)
Product.create(name: "Air Max 90", price: 150.00, description: "Nike Air Max 90", supplier_id: 1)
Product.create(name: "Air Force One", price: 140.00, description: "Nike Air Force 1s", supplier_id: 1)
Product.create(name: "Adizero", price: 130.00, description: "Adidas Adizero", supplier_id: 2)
Product.create(name: "Ultraboost", price: 180.00, description: "Adidas Ultraboost", supplier_id: 2)